#from a list, print every barcelona player
barcelona_players = [
"Lionel Messi",
"Xavi Hernandez",
"Andres Iniesta",
"Johan Cruyff",
"Ronaldinho",
"Samuel Eto'o",
"Ronaldo Nazario",
"Ronald Koeman",
"Michael Laudrup",
"Cesar Rodriguez",
"Sergio Busquets",
"Carles Puyol",
"Diego Maradona",
"Gerard Pique",
"Luis Suarez",
"Rivaldo",
"Pep Guardiola",
"Neymar",
"Luis Suarez Miramontes",
"Victor Valdes",
"Marc-André ter Stegen",
"Jordi Alba",
"Dani Alves",
"Patrick Kluivert",
"Deco",
"Thierry Henry",
"Hristo Stoichkov",
"Gary Lineker",
"Frank de Boer",
"Edgar Davids",
"Rafael Márquez",
"Ivan Rakitic",
"David Villa",
"Alexis Sanchez",
"Javier Mascherano",
"Cesc Fabregas",
"Arthur Melo",
"Antoine Griezmann",
"Frenkie de Jong",
"Pedri",
"Ansu Fati",
"Lamine Yamal",
"Ferran Torres",
"Ousmane Dembélé",
"Eric Abidal",
"Sylvinho",
"Giovanni van Bronckhorst",
"Belletti",
"Thomas Vermaelen",
"Samuel Umtiti",
"Nelson Semedo",
"Clément Lenglet",
"Sergi Roberto",
"Sergi Barjuan",
"Albert Ferrer",
"Miguel Ángel Nadal",
"Guillermo Amor",
"Txiki Begiristain",
"Julio Salinas",
"Eusebio Sacristán",
"Andoni Zubizarreta",
"Francisco José Carrasco",
"Víctor Muñoz",
"Steve Archibald",
"Bernd Schuster",
"Allan Simonsen",
"Quini",
"Juan Manuel Asensi",
"Carles Rexach",
"José Mari Bakero",
"Ion Andoni Goikoetxea",
"Julio Alberto",
"José Ramón Alexanko",
"José Vicente Sánchez",
"Ricardo Serna",
"Francisco Javier Urruticoechea",
"Juan Carlos Unzué",
"Albert Celades",
"Luis Enrique",
"Abelardo Fernández",
"Juan Antonio Pizzi",
"Sonny Anderson",
"Christophe Dugarry",
"Giovanni Silva",
"Winston Bogarde",
"Phillip Cocu",
"Boudewijn Zenden",
"Jari Litmanen",
"Ronald de Boer",
"Gabri García",
"Luis Figo",
"Simão Sabrosa",
"Alfonso Pérez",
"Emmanuel Petit",
"Marc Overmars",
"Gerard López",
"Dani García",
"Javier Saviola",
"Juan Román Riquelme",
"Ludovic Giuly",
"Henrik Larsson",
"Pedro Rodríguez",
"Philippe Coutinho",
"Arthur Melo",
"Martin Braithwaite",
"Adama Traoré",
"Memphis Depay",
"Luuk de Jong"
# ... (extend as needed for more historical players)
]
